name: Dependency Updates

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy ci-gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: access TMDB_API_KEY
        env:
          TMDB_API_KEY: ${{secrets.TMDB_API_KEY}}
        run: echo tmdb_api_key=\"$TMDB_API_KEY\" > ./local.properties

      - name: access TRAKT_CLIENT_ID
        env:
          TRAKT_CLIENT_ID: ${{secrets.TRAKT_CLIENT_ID}}
        run: echo trakt_client_id=\"$TRAKT_CLIENT_ID\" > ./local.properties

      - name: access TRAKT_CLIENT_SECRET
        env:
          TRAKT_CLIENT_SECRET: ${{secrets.TRAKT_CLIENT_SECRET}}
        run: echo trakt_client_secret=\"$TRAKT_CLIENT_SECRET\" > ./local.properties

      - name: Check dependency updates
        run: ./gradlew dependencyUpdates

      - name: Upload dependency updates report
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates