name: Dependency Updates

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TERM: dumb
      TMDB_API_KEY: ${{secrets.TMDB_API_KEY}}
      TRAKT_CLIENT_ID: ${{secrets.TRAKT_CLIENT_ID}}
      TRAKT_CLIENT_SECRET: ${{secrets.TRAKT_CLIENT_SECRET}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy ci-gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Write app secrets to local.properties
        run: |
          echo TRAKT_CLIENT_ID=\"$TRAKT_CLIENT_ID\" > ./local.properties
          echo TMDB_API_KEY=\"$TMDB_API_KEY\" >> ./local.properties
          echo TRAKT_CLIENT_SECRET=\"$TRAKT_CLIENT_SECRET\" >> ./local.properties

      - name: Show local.properties contents
        run: |
          ls -la
          cat local.properties

      - name: Check dependency updates
        run: ./gradlew dependencyUpdates

      - name: Upload dependency updates report
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates